# Generated by Django 2.0 on 2017-12-25 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_mymodelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('310a32e8-484f-436c-bb03-96cd3d56fc1d'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
