# Generated by Django 2.0 on 2017-12-30 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171230_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d166052-07bd-4b6e-bcb7-f51a97ae7f1b'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
