# Generated by Django 2.0 on 2017-12-30 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171230_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7292c531-331d-435c-8308-c59cb00da2bb'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
