# Generated by Django 2.0 on 2017-12-31 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20171230_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0da864ad-843a-4815-9173-5d3907369a30'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
