# Generated by Django 2.0 on 2018-01-01 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180101_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5fde1843-7797-4f79-b2a8-00574d229f33'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
