# Generated by Django 2.0 on 2018-01-01 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180101_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_borrowed', 'View all borrowed books'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0d5dd44-45e8-48a7-9a50-464a22cb8c17'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
