# Generated by Django 2.0 on 2018-01-01 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180101_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_borrowed', 'View all borrowed books'), ('can_renew', 'Renew borrowed books'))},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2a29ad9-a5e1-41a1-a0e7-ee7a5254162d'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
