# Generated by Django 2.0 on 2018-01-01 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180101_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4db0027f-396f-4131-a379-cb473aadc28d'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
